apiVersion: v1
kind: Service
metadata:
  name: jetson-service
spec:
  selector:
    app: jetson-python
  ports:
  - protocol: "TCP"
    port: 16000
    targetPort: 5002
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetson-python
spec:
  selector:
    matchLabels:
      app: jetson-python
  replicas: 2
  template:
    metadata:
      labels:
        app: jetson-python
    spec:
      hostNetwork: true
      schedulerName: my-scheduler
      containers:
      - name: jetson-python
        image: dustynv/jetson-inference:r32.6.1
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        ports:
        - containerPort: 5002
      restartPolicy: Always